--- 
- 
  connection: local
  hosts: localhost
  name: "installing MLOps setup environment"
  tasks: 
    - 
      apt: 
        name: "{{packages}}"
        state: present
      become: true
      name: "install required tools and packages"
      vars: 
        packages: 
          - git
          - python3-pip
          - docker
          - docker-compose
    - 
      become: true
      name: "installing python packages with pip"
      pip: 
        name: "{{package}}"
        state: present
      vars: 
        package: 
          - dvc
          - mlflow
          - mlflow-dbstore
          - flask
          - cloudpickle
          - pysqlite3
          - configparser
          - cookiecutter